<script lang="ts">
  import { onMount } from 'svelte'

  import Map from 'ol/Map.js'
  import TileLayer from 'ol/layer/Tile.js'
  import XYZ from 'ol/source/XYZ.js'
  import View from 'ol/View.js'
  import { fromLonLat } from 'ol/proj.js'

  import { WarpedMapLayer } from '../lib/WarpedMapLayer'
  import { WarpedMapSource } from '../lib/WarpedMapSource'

  import { generateId } from '@allmaps/id/browser'
  import { parseAnnotation } from '@allmaps/annotation'

  let ol
  let xyz
  let baseLayer
  let warpedMapLayer: WarpedMapLayer
  let warpedMapSource: WarpedMapSource

  let imageUris = [
    'https://cdm21033.contentdm.oclc.org/digital/iiif/krt/1022',
    'https://cdm21033.contentdm.oclc.org/digital/iiif/krt/1649',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:m900rh51m',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:ms35v598x',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:m900rd464',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c498r',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c252q',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bz82n',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:tm70rv15c',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9s161f22q',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:z603vj31d',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:0z7095830',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9g54xw13f',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9s161h46q',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:0z709802d',

    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:0r96fq33d',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c0180',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c0287',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c034c',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bp307',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c026p',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c0244',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c072s',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c0707',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bp14v',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c014w',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c192g',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:0r96fp999',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bp36w',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bp00h',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c0201',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bp34b',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c038g',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bn964',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:0r96fn968',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c178n',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c286j',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257br70m',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257br92n',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c296s',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:0r96fn526',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bx840',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bx86j',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:hx11z017m',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c148x',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c130g',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c1321',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c146c',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bt22c',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257br725',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bx82f',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:js956k939',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bx548',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bx726',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bz226',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bz18m',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bx70n',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bz20n',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bx74r',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c044m',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c062j',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c058z',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c056d',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c0643',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c048q',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c066n',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c0600',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c076w',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bn98p',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c0465',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:q524n431x',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bt26g',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bt36q',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bt48h',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bt345',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bt46z',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bt50j',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bt566',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bt58r',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bt24x',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bt523',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bt60s',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bt54n',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bt44d',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bt744',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bt72k',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bt62b',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bt64w',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:0r96fm72g',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:7h14b218h',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:z603vj682',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:m900rf851',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:4m90f767c',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:tm70rz72m',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:tm70rz71b',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:tm70rv31r',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:tm70rw972',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:tm70rv90x',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:tm70rv916',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:tm70rv39z',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:tm70rv097',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:tm70rz67r',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:tm70rt155',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:tm70s092g',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:tm70rz877',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:tm70s017x',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:tm70rv38p',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:tm70s0649',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:tm70s019g',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:tm70s0100',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:tm70rs388',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:tm70s026w',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:tm70rs50j',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:tm70rz699',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:tm70s053s',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:tm70rs434',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:tm70rs523',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:tm70rv15c',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:tm70rw12r',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:tm70rv720',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:tm70rw11g',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:tm70rv92g',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:tm70rs39j',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:tm70rt88p',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:tm70rz656',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:ht250b18k',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:ht2502862',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:ht250921p',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:ht250c55x',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:ht250c302',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:ht250887k',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:ht250b802',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:ht250b909',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:ht250b624',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9g54z6461',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9g54xr76w',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9g54xr74b',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9g54z279r',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9g54xv79b',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9g54xv81c',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:ht250602v',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:ht250b82m',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9g54xr72s',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:ht250682s',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9g54xr80g',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9g54xr821',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:ht250650h',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9g54xv83x',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9g54xv85g',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9g54z283b',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9g54z285w',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:ht2506009',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9g54xt972',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9g54xv714',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9g54xx94v',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9g54xw036',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9g54xv315',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9g54xw85p',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9g54xv91m',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9g54xs81z',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9g54xs100',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9g54xv49m',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9g54xv693',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9g54xv935',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9g54xv89k',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9g54xv978',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9g54xv73p',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:js957748k',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:js957744g',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9g54xw01n',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9g54xv27k',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9g54z684f',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9g54xv871',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9g54z269h',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9g54xv757',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9g54xv95q',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9g54xv99t',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:js957750m',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:js957742x',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:js957762d',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:js957740c',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:js957758t',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9g54xv294',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9g54xv33q',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9g54xv358',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9g54xr78f',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:hx11z3223',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9g54xt16v',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9g54xt28n',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9g54xt18d',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9g54z281s',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9g54z334m',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:ht250666d',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9g54z648k',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9g54z344v',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9g54z313v',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:tm70rv75t',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9g54z6746',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:ht250105n',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:ht250117f',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:ht24zz08r',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:cj82ks32j',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:t722hs61v',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:0z709651x',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:0z709653g',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9s161953w',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:3f463574k',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:hx11xz49h',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:js956j10b',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:z603vj31d',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9s161j743',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:q524mv10b',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:0z7095830',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9g54xw13f',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9s161h46q',

    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:3f4631085',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:x633fb53d',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:x059c9259',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:hx11z572q',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:hx11z264d',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:hx11z5684',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bx56t',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bs268',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bs08b',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bs42n',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bz24r',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bt14p',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bs02p',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bs12x',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bs20m',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bs32d',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bs403',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c108z',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bq80n',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bs004',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bs382',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bt10k',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bt922',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bt32m',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bz14h',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bt167',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c104v',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bt18s',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bs36h',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bs28t',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bs34z',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bs047',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bz12z',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bt20t',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257br74q',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c2883',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c448j',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c2441',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bw96k',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bx042',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c2220',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bx06m',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c2548',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bx085',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c242g',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bx12r',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bw90x',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bx220',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bx24j',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bx263',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c246k',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bx149',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bw92g',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bw941',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bx106',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bx64h',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bx92p',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bx662',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bx68m',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bx769',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c2947',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bx883',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bx904',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bx80w',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bx58c',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c482v',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c484d',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c426h',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c414q',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c410m',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c422d',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c390b',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c516g',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c512c',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c3889',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c5067',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c444f',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c400c',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c486z',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c4125',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c398j',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c508s',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c402x',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c386r',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c424z',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c510t',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c514x',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c012b',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bt08j',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c004n',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bz162',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c3561',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c348b',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c346s',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c0066',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c0023',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bw52h',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c318m',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c476q',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bt124',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c404g',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bw48x',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c3226',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c3005',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:hx11z053g',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257br86h',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c350c',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c074b',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c352x',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c460t',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257br84z',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c458s',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bn786',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bn807',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c298b',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c2484',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c360m',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c342p',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c186b',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c184s',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c5024',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bs30v',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bp243',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c504p',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c3447',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bz10d',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c190x',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bp22j',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c4460',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c3340',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c3383',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c3269',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c336j',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bz005',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bs24q',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bx96s',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bs18k',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257br989',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c330w',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bs14g',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bx947',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c320n',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c450k',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c332f',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c3404',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c328v',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bx98b',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bz06t',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bs161',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c488h',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bz02q',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bs10c',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bs225',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bs06s',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bz08c',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257br78t',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257br82d',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257br946',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257br768',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c324r',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bz048',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c490j',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c4923',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c364q',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c374z',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c376h',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c3625',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c372d',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c432n',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c4389',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c408k',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c3782',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c4061',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c420v',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c418t',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c4303',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c370v',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c4168',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c4282',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c436r',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c368t',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c3668',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c4346',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bq28d',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c500k',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bz46s',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bz340',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bx441',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bz447',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c3162',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bx484',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c280w',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c2106',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c206m',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bx327',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c1984',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c196k',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bx28n',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bx30p',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bx42g',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c270n',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c2662',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bx40x',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bx46k',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c278v',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c168d',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c174j',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c1720',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c170f',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c268m',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c166v',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bn921',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c472m',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c312z',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c230p',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bz803',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c116n',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c1207',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c2263',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c234s',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bt701',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bt409',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c256t',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c258c',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c236b',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c228n',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c238w',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c240x',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c2327',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c224j',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c3960',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bn64v',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bt281',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bt66f',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bt302',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bt42v',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bt680',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bt388',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c128f',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bp286',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bz58k',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bz82n',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c252q',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bz98j',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bz92w',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c2840',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c498r',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c4809',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c4966',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c4788',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c494n',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c4681',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c454p',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c382n',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c464x',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c4745',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c4524',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c308c',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c466g',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c392w',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c394f',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c3803',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c3846',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c4702',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c4567',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c462c',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c306t',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c2904',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c292p',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bx18d',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bp065',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c156m',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c1649',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bv32t',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bv422',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bz54g',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bv821',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bx36b',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bx20f',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bx38w',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bw984',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bx02h',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bx16v',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bx00z',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bz42p',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bw100',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bp10r',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bp08q',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bp129',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bp04m',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bp022',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c134k',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c1364',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bn66d',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bn88f',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bn72j',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c144t',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c262z',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bz782',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c354g',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bz383',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bz60m',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bz625',
    'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bz64q'
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bz74z',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bz404',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bz90b',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bz846',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bz52x',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bz86r',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bz76h',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bz72d',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bz889',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bz50c',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bx34s',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bq940',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bz30w',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c138p',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bn84b',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bn700',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bn94k',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bn76n',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bn86w',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c1606',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c1585',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c090q',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c100r',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c094t',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c096c',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c112j',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c1029',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c1100',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c098x',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c1143',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c0864',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c264h',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c260d',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c274r',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bx52q',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:0r96fn925',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:0r96fn98t',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:0r96fn50n',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:0r96fk56w',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:0r96fn330',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:0r96fk73j',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c140q',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c078f',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:0r96fm848',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:0r96fp671',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c022k',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:0r96fm032',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c0308',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c040h',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257bp16d',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c314h',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257br903',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257br882',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c3048',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c302q',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c126w',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:0r96fn373',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:0r96fk24m',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:0r96fp026',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c124b',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c1428',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c0422',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c032t',
    // 'https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:1257c0529'
  ]

  // imageUris = ['https://iiif.digitalcommonwealth.org/iiif/2/commonwealth:9s161f22q']

  // imageUris = [
  //   'https://cdm21033.contentdm.oclc.org/digital/iiif/krt/6014',
  //   'https://cdm21033.contentdm.oclc.org/digital/iiif/krt/6015',
  // ]

  let opacity = 1

  $: {
    warpedMapLayer?.setOpacity(opacity)
  }

  async function addMapByImageUri(imageUri: string) {
    const imageId = await generateId(imageUri)
    const apiUrl = `https://dev.api.allmaps.org/images/${imageId}/maps`
    const maps = await fetch(apiUrl).then((response) => response.json())

    if (Array.isArray(maps)) {
      maps.forEach((map) => {
        warpedMapSource.addMap(map)
      })
    }
  }

  onMount(async () => {
    const tileUrl =
      'https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}'

    xyz = new XYZ({
      url: tileUrl,
      maxZoom: 19
    })

    baseLayer = new TileLayer({
      source: xyz
    })

    warpedMapSource = new WarpedMapSource()
    warpedMapLayer = new WarpedMapLayer({
      source: warpedMapSource
    })

    ol = new Map({
      layers: [baseLayer, warpedMapLayer],
      target: 'ol',
      view: new View({
        center: fromLonLat([-71.13, 42.2895]),
        maxZoom: 22,
        zoom: 17
      })
    })

    const annotationsResponse = await fetch('../annotations.json')
    const annotations = await annotationsResponse.json()
    const maps = parseAnnotation(annotations)

    for (let map of maps) {
      warpedMapSource.addMap(map)
    }

    // for (let imageUri of imageUris) {
    //   addMapByImageUri(imageUri)
    // }
  })
</script>

<div class="container">
  <div id="ol" />
  <div class="controls">
    <input type="range" bind:value={opacity} min="0" max="1" step="0.01" />
  </div>
</div>

<style>
  :global(body),
  :global(#svelte) {
    margin: 0;
    position: absolute;
    width: 100%;
    height: 100%;
  }

  .container {
    width: 100%;
    height: 100%;
    display: flex;
    flex-direction: row;
  }

  .container > * {
    width: 100%;
    height: 100%;
  }

  .controls {
    position: absolute;
    background: white;
    width: 300px;
    bottom: 0;
    height: 20px;
    padding: 5px;
    border-radius: 5px;
  }

  #ol {
    width: 100%;
    height: 100%;
  }
</style>
